export const routeMappings = [
    {
        gatewayPath: '/user/login',
        targetPath: '/auth/login',
        service: 'auth',
        method: 'POST',
        protected: false,
        validatePayload: true,
    },
    {
        gatewayPath: '/user/register',
        targetPath: '/auth/register',
        service: 'auth',
        method: 'POST',
        protected: false,
        validatePayload: false,
    },
    {
        gatewayPath: '/users/one/:id',
        targetPath: '/auth/one/:id',
        service: 'auth',
        method: 'GET',
        protected: false,
        validatePayload: false,
    },
    {
        gatewayPath: '/users/all',
        targetPath: '/users/all',
        service: 'data',
        method: 'GET',
        protected: false,
        validatePayload: false,
    },
    {
        gatewayPath: '/users/update/:id',
        targetPath: '/users/update/:id',
        service: 'data',
        method: 'PUT',
        protected: false,
        validatePayload: true,
    },
    {
        gatewayPath: '/users/delete/:id',
        targetPath: '/users/delete/:id',
        service: 'data',
        method: 'DELETE',
        protected: false,
        validatePayload: false,
    },
];
